backend:
  name: github
  repo: mpanko/denisasvach
  branch: main
  base_url: https://sveltia-cms-auth.yellowzelo.workers.dev/

local_backend: true

media_folder: public/images
public_folder: /images

webhook:
  url: https://mpanko.github.io/denisasvach/api/rename-project-files

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{id}}"
    identifier_field: "id"
    clean_accents: true
    fields:
      - {label: "Project ID", name: "id", widget: "string", pattern: ['^[a-z0-9]+(?:-[a-z0-9]+)*$', "Must be lowercase letters, numbers, and hyphens only"]}
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Thumbnail Image", name: "image", widget: "image"}
      - {label: "Project Description", name: "description", widget: "text"}
      - label: "Project Content"
        name: "content"
        widget: "list"
        required: true
        min: 1
        max: 100
        types:
          - label: "Text"
            name: "text"
            widget: "object"
            fields:
              - {label: "Type", name: "type", widget: "hidden", default: "text"}
              - {label: "Content", name: "content", widget: "markdown", editor_components: [], buttons: ["bold", "italic", "link"]}
          - label: "Image"
            name: "image"
            widget: "object"
            fields:
              - {label: "Type", name: "type", widget: "hidden", default: "image"}
              - {label: "Source", name: "src", widget: "image"}
              - {label: "Image Description", name: "alt", widget: "string"}
              - {label: "Span Full Width", name: "span", widget: "boolean", default: false, required: false}
          - label: "YouTube"
            name: "youtube"
            widget: "object"
            fields:
              - {label: "Type", name: "type", widget: "hidden", default: "youtube"}
              - {label: "YouTube ID", name: "youtubeId", widget: "string"}
              - {label: "Span Full Width", name: "span", widget: "boolean", default: false, required: false}
          - label: "SoundCloud"
            name: "soundcloud"
            widget: "object"
            fields:
              - {label: "Type", name: "type", widget: "hidden", default: "soundcloud"}
              - {label: "SoundCloud URL", name: "soundcloudUrl", widget: "string"}
              - {label: "Span Full Width", name: "span", widget: "boolean", default: false, required: false}
              
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/bio.md"
        label: "Bio"
        name: "bio"
        fields:
          - label: "Sections"
            name: "sections"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - label: "Items"
                name: "items"
                widget: "list"
                fields:
                  - {label: "Year", name: "year", widget: "string"}
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "Institution", name: "institution", widget: "string", required: false}
                  - {label: "Location", name: "location", widget: "string", required: false}
                  - {label: "Type", name: "type", widget: "string", required: false}
                  - {label: "Description", name: "description", widget: "string", required: false}
          - {label: "Content", name: "body", widget: "markdown", editor_components: [], buttons: ["bold", "italic", "link"]}

      - file: "content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Content", name: "body", widget: "markdown", editor_components: [], buttons: ["bold", "italic", "link"]}